name: Auto Zip Resources

on:
  workflow_run:
    workflows: ["Auto Convert Images To WebP"]
    types:
      - completed

permissions:
  contents: write

jobs:
  zip:
    name: Zip Resources
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 1

      - name: Pull latest changes
        run: git pull origin master

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Generate zip file
        run: python generate_zipfile.py

      - name: Commit updated zip
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: ':wrench: auto zip resources [skip ci]'
          add: |
            'miraita-resources.zip'